spring:
  application:
    name: ms.credit-manager
  datasource:
    url: jdbc:postgresql://localhost:5441/postgres
    username: postgres
    password: postgres
  data:
    web:
      pageable:
        default-page-size: 12
  jpa:
    open-in-view: false
    show-sql: true